#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------
# reset simulation
cleanCase

rm -rf constant/triSurface
rm -rf constant/extendedFeatureEdgeMesh

# delete 0 directory
rm -r 0

# remove computed cell centers
rm constant/C*
rm constant/V
#------------------------------------------------------------------------------
