#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${ML_CFD_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------
# reset simulation
cleanCase

rm -rf constant/triSurface
rm -rf constant/extendedFeatureEdgeMesh

# delete 0 directory
rm -r 0
#------------------------------------------------------------------------------
