#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${ML_CFD_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

cleanCase

rm -rf constant/boundaryData
rm -f *.png
rm -r 0

# -----------------------------------------------------------------------------
