#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

cleanCase

rm -rf constant/boundaryData
rm -f *.png
rm -r 0

# remove computed cell centers
rm constant/C*
rm constant/V

# -----------------------------------------------------------------------------
