#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

# reset simulation
cleanCase

# delete o directory
rm -r 0

rm *.txt

# remove computed cell centers
rm constant/C*
rm constant/V
#------------------------------------------------------------------------------
