#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

# reset simulation
cleanCase

# delete o directory
rm -r 0

# remove computed cell centers
rm constant/C*
rm constant/V

# remove trajectory
rm *.txt

# restore fvSolution
cp system/fvSolution.orig system/fvSolution
rm system/fvSolution.orig
#------------------------------------------------------------------------------
