#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${ML_CFD_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

# restore the 0 directory
# restore0Dir
cp -r 0.orig 0

# mesh creation with blockMesh
runApplication blockMesh

# set fields
runApplication setFields

# run checkMesh
runApplication checkMesh

# decompose case
runApplication decomposePar

# dummy file for post-processing
touch post.foam

# execute flow solver
runParallel $(getApplication)

# reconstruct
runApplication reconstructPar

# clean up
rm -r processor*

# for flowtorch, it it faster to do computations within openfoam
postProcess -func "writeCellCentres" -constant -time none > log.writeCellCentres
postProcess -func "writeCellVolumes" -constant -time none > log.writeCellVolumes
