#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------
# restore0Dir
cp -r 0.orig 0

runApplication blockMesh

runApplication boundaryFoam

# -----------------------------------------------------------------------------
