#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

# Run a precursor channel flow to create a fully developed flow profile for the
# main case
(cd initChannel && ./Allrun)

# Run the main case
(cd fullCase && ./Allrun)
# ------------------------------------------------------------------------------
