#!/bin/bash
cd "${0%/*}" || exit
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

cleanCase
rm -r 0

# remove computed cell centers
rm constant/C*
rm constant/V

rm *.txt
#------------------------------------------------------------------------------
