#!/bin/bash
cd "${0%/*}" || exit
. ${ML_CFD_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

cleanCase
rm -r 0

# remove computed cell centers
rm constant/C*
rm constant/V
#------------------------------------------------------------------------------
