#!/bin/bash
cd "${0%/*}" || exit
. ${DRL_BASE}/RunFunctions        # run functions
#------------------------------------------------------------------------------

# mesh creation
runApplication blockMesh

# run checkMesh
runApplication checkMesh

# set inlet velocity
cp -r 0.org 0
runApplication setExprBoundaryFields

# decompose case
runApplication decomposePar
runParallel renumberMesh -overwrite

# dummy file for post-processing
touch post.foam

# execute flow solver
runParallel $(getApplication)

# reconstruct
runApplication reconstructPar

# clean up
rm -r processor*

# for flowtorch, it it faster to do computations within openfoam
postProcess -func "writeCellCentres" -constant -time none > log.writeCellCentres
postProcess -func "writeCellVolumes" -constant -time none > log.writeCellVolumes
#------------------------------------------------------------------------------
